project:
  type: website
  output-dir: _output
  resources:
    - graph_big/visuals/fa2_graphbig.html
    - graph_big/visuals/fa2_categorygraph.html
    - graph_big/visuals/fa2_greygraph.html
    - graph_big/visuals/fa2_biggraph.json
    - graph_big/visuals/hairball.html
    - graph_big/visuals/hairball.json

website:
  title: "Graphdatenvisualisierung"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
